#!/usr/bin/python3

from time import strptime
from datetime import datetime
import locale
import sys

from bs4 import BeautifulSoup
from icalendar import Calendar, Event


YEAR = 2022
SUBSCRIPTION = ['K12', 'K26', 'K52']
LEGEND = {
    'K12': 'Komunálny odpad, mesačný vývoz, čierna nádoba',
    'K26': 'Komunálny odpad, dvojtýždenný vývoz, čierna nádoba',
    'K52': 'Komunálny odpad, týždenný vývoz, čierna nádoba',
    'PKV': 'Plasty, tetrapaky, kovy, konzervy, plechovky, VKM',
    'PAP': 'Papier, kartón',
    'BIO': 'Tráva, lístie, konáre, šupky, zelenina, ovocie',
    'KU':  'Kuchynský odpad',
}
NAMES = {
    'K12': 'Čierna nádoba mesačný',
    'K26': 'Čierna nádoba dvojtýždenný',
    'K52': 'Čierna nádoba týždenný',
    'PKV': 'Žltá nádoba',
    'PAP': 'Modrá nádoba',
    'BIO': 'Hnedá nádoba',
    'KU':  'Kuchynský odpad',
}


def create_event(cal, codes):
    event = Event()
    names = [NAMES[i] for i in codes]
    description = ['- ' + LEGEND[i] for i in codes]
    event.add('summary', 'Odpad: ' + ', '.join(names))
    event.add('description', '\n'.join(description))
    event.add('dtstart', date)
    event.add('dtend', date)
    #event.add('dtstamp', )
    return event


with open(sys.argv[1]) as f:
	html = f.read()

soup = BeautifulSoup(html, 'html.parser')
tables = [
    [
        [td.get_text(strip=True) for td in tr.find_all('td')]
        for tr in table.find_all('tr')
    ]
    for table in soup.find_all('table')
]

assert len(tables) == 1  # we're only expecting one table
table = tables[0]

locale.setlocale(locale.LC_ALL, 'sk_SK.utf8')

cal = Calendar()
cal.add('attendee', 'MAILTO:abc@example.com')

month = None
day = None
for row in table:
    if not row:
        continue
    if len(row) == 1:
        #import ipdb; ipdb.set_trace()
        month = row[0]
        if not month:
            continue
        month = strptime(month[:3], '%b').tm_mon
        continue
    col = row[0]
    try:
        day = int(col)
    except:
        continue
    if len(row) <= 4:
        continue
    date = datetime.strptime(
        '%i%i%2i' % (YEAR, month, day),
        '%Y%m%d').date()
    codes = [i for i in row[2:8] if i != 'X']
    event = create_event(cal, codes)
    cal.add_component(event)

with open(sys.argv[2], 'wb') as f:
    f.write(cal.to_ical())
