#!/usr/bin/python3

from time import strptime
from datetime import datetime
import locale
import sys

from bs4 import BeautifulSoup
from icalendar import Calendar, Event


SUBSCRIPTION, HTML_FILE, ICS_FILE = sys.argv[1:4]
YEAR = 2022
LEGEND = {
    'K12': 'Komunálny odpad, mesačný vývoz, čierna nádoba',
    'K26': 'Komunálny odpad, dvojtýždenný vývoz, čierna nádoba',
    'K52': 'Komunálny odpad, týždenný vývoz, čierna nádoba',
    'PKV': 'Plasty, tetrapaky, kovy, konzervy, plechovky, VKM',
    'PAP': 'Papier, kartón',
    'BIO': 'Tráva, lístie, konáre, šupky, zelenina, ovocie',
    'KU':  'Kuchynský odpad',
}
NAMES = {
    'K12': 'čierny',
    'K26': 'čierny',
    'K52': 'čierny',
    'PKV': 'žltý',
    'PAP': 'modrý',
    'BIO': 'hnedý',
    'KU':  'kuchynský',
}


def create_event(cal, codes):
    event = Event()
    names = [NAMES[i] for i in codes]
    description = ['- ' + LEGEND[i] for i in codes]
    event.add('summary', 'Odpad: ' + ' + '.join(names))
    event.add('description', '\n'.join(description))
    event.add('dtstart', date)
    event.add('dtend', date)
    #event.add('dtstamp', )
    return event


with open(HTML_FILE) as f:
	html = f.read()

soup = BeautifulSoup(html, 'html.parser')
tables = [
    [
        [td.get_text(strip=True) for td in tr.find_all('td')]
        for tr in table.find_all('tr')
    ]
    for table in soup.find_all('table')
]

assert len(tables) == 1  # we're only expecting one table
table = tables[0]

locale.setlocale(locale.LC_ALL, 'sk_SK.utf8')

cal = Calendar()
cal.add('attendee', 'MAILTO:abc@example.com')

month = None
day = None
for row in table:
    if not row:
        continue
    if len(row) == 1:
        #import ipdb; ipdb.set_trace()
        month = row[0]
        if not month:
            continue
        month = strptime(month[:3], '%b').tm_mon
        continue
    col = row[0]
    try:
        day = int(col)
    except:
        continue
    if len(row) <= 4:
        continue
    date = datetime.strptime(
        '%i-%i-%i' % (YEAR, month, day),
        '%Y-%m-%d').date()

    codes = []
    for i in row[2:8]:
        if i == 'X':
            continue
        if i[0] == 'K' and i != 'KU' and i != SUBSCRIPTION:
            continue
        codes.append(i)
    if not codes:
        continue

    event = create_event(cal, codes)
    cal.add_component(event)

with open(ICS_FILE, 'wb') as f:
    f.write(cal.to_ical())
