#!/usr/bin/python3

from time import strptime
from datetime import datetime
import locale
import sys

from bs4 import BeautifulSoup
from icalendar import Calendar, Event


URL = 'https://grimmaldus.github.io/chorvatan-garbage/'
SERVICE, HTML_FILE = sys.argv[1:3]
SEQUENCE = 0  # Managed by Makefile, just use 0 here
YEAR = 2023
NAMES = {
    'F12': 'čierny',
    'F26': 'čierny',
    'F52': 'čierny',
    'PKV': 'žltý',
    'PAP': 'modrý',
    'BIO': 'BIO',
    'KU':  'kuchynský',
}
LEGEND = {
    'F12': 'Komunálny odpad, mesačný vývoz, čierna nádoba',
    'F26': 'Komunálny odpad, dvojtýždenný vývoz, čierna nádoba',
    'F52': 'Komunálny odpad, týždenný vývoz, čierna nádoba',
    'PKV': 'Plasty, tetrapaky, kovy, konzervy, plechovky, VKM',
    'PAP': 'Papier, kartón',
    'BIO': 'Tráva, lístie, konáre, šupky, zelenina, ovocie',
    'KU':  'Kuchynský odpad',
}


def create_event(date, codes):
    event = Event()
    names = [NAMES[i] for i in codes]
    description = ['- ' + LEGEND[i] for i in codes] + \
                  ['', 'Zdroj: ' + URL]
    event.add('summary', 'Odpad: ' + ' + '.join(names))
    event.add('description', '\n'.join(description))
    event.add('dtstart', date)
    event.add('dtend', date)
    event.add('dtstamp', datetime.now())
    event.add('UID', date.strftime('%Y%m%d') + '@chorvatan.sk')
    event.add('sequence', SEQUENCE)
    return event


with open(HTML_FILE) as f:
	file = f.read()
soup = BeautifulSoup(file, 'html.parser')
tables = [
    [
        [td.get_text(strip=True) for td in tr.find_all('td')]
        for tr in table.find_all('tr')
    ]
    for table in soup.find_all('table')
]

assert len(tables) == 1  # we're only expecting one table
table = tables[0]

locale.setlocale(locale.LC_ALL, 'sk_SK.utf8')

cal = Calendar()

month = None
day = None
for row in table:
    if not row:
        continue
    if len(row) == 1:
        month = row[0]
        if not month:
            continue
        month = strptime(month[:3], '%b').tm_mon
        continue
    try:
        day = int(row[0])
    except:
        continue
    if len(row) <= 4:
        continue
    date = datetime.strptime(
        '%i-%i-%i' % (YEAR, month, day),
        '%Y-%m-%d').date()

    codes = []
    for col in row[2:]:
        if col not in NAMES:
            continue
        if col.startswith('F') and col != SERVICE:
            continue
        codes.append(col)
    if not codes:
        continue

    event = create_event(date, codes)
    cal.add_component(event)

print(cal.to_ical().decode('utf-8'))
